### 
GET http://localhost:3000/products/current_stock

###

// Request to register an user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "admin3",
  "password": "pass",
  "email":"admin@localhost.com"
}

###
// Request to log-in
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin3",
  "password": "pass"
}
